FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# NLTK stopwords for sumy
RUN python -c "import nltk; nltk.download('punkt', quiet=True); nltk.download('stopwords', quiet=True)"

# Pre-pull NLP models so first request is fast (~2 GB total)
# NER: PlanTL RoBERTa fine-tuned on Spanish news
RUN python -c "from transformers import pipeline; pipeline('token-classification', model='PlanTL-GOB-ES/roberta-base-bne-ner-capiter', aggregation_strategy='simple')"
# Relevance + scope + topic classification (NLI)
RUN python -c "from transformers import pipeline; pipeline('zero-shot-classification', model='Recognai/bert-base-spanish-wwm-cased-xnli')"
# Dedup + semantic embeddings
RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')"

COPY . /app/

# Explicit guard: fail the build if required data/config files are missing.
# geonames_es.tsv and cities_snapshot.json are generated by the build scripts (not committed).
# street_index.json and source_city_prior.json are committed stubs (empty = no street lookup yet).
RUN test -f /app/nlp/geotagger/data/geonames_es.tsv && \
    test -f /app/nlp/geotagger/data/cities_snapshot.json && \
    test -f /app/config/topics.yaml && \
    test -f /app/config/street_index.json && \
    test -f /app/config/source_city_prior.json

EXPOSE 8000
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
